--liquibase formatted sql

--changeset pavel-kupreichik:001-create-users-table
CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100)             NOT NULL,
    surname     VARCHAR(100)             NOT NULL,
    birth_date  DATE                     NOT NULL,
    email       VARCHAR(255)             NOT NULL,
    active      BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

--rollback DROP TABLE users;
