--liquibase formatted sql

--changeset pavel-kupreichik:002-create-payment-cards-table
CREATE TABLE payment_cards
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT                   NOT NULL,
    number          VARCHAR(19)              NOT NULL,
    holder          VARCHAR(255)             NOT NULL,
    expiration_date DATE                     NOT NULL,
    active          BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_payment_cards PRIMARY KEY (id),
    CONSTRAINT fk_payment_cards_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
);

--rollback DROP TABLE payment_cards;
