spring:
  application:
    name: user-service

  cache:
    type: redis
    cache-names:
      - user-details

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml